/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'valuation' : string,
  'updatedAt' : bigint,
  'locationLink' : string,
  'location' : string,
}
export type PropertyStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SmartFinanceRequest {
  'request' : string,
  'user' : Principal,
  'timestamp' : bigint,
}
export type SmartFinanceRole = { 'financeApproved' : null } |
  { 'standard' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getApprovedProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinanceRoles' : ActorMethod<[], Array<[Principal, SmartFinanceRole]>>,
  'getMyProperties' : ActorMethod<[], Array<Property>>,
  'getSmartFinanceRequests' : ActorMethod<[], Array<SmartFinanceRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerFinanceApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestSmartFinanceAccess' : ActorMethod<[string, bigint], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPropertyStatus' : ActorMethod<
    [bigint, PropertyStatus, bigint],
    undefined
  >,
  'setSmartFinanceRole' : ActorMethod<[Principal, SmartFinanceRole], undefined>,
  'submitContactSubmission' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitProperty' : ActorMethod<
    [string, string, string, string, string, bigint],
    bigint
  >,
  'updateProperty' : ActorMethod<
    [bigint, string, string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];