/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'valuation' : string,
  'updatedAt' : bigint,
  'locationLink' : string,
  'location' : string,
  'photos' : Array<string>,
}
export type PropertyStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SmartFinanceRequest {
  'request' : string,
  'user' : Principal,
  'timestamp' : bigint,
}
export type SmartFinanceRole = { 'financeApproved' : null } |
  { 'standard' : null };
export interface SubmitPropertyInput {
  'title' : string,
  'description' : string,
  'valuation' : string,
  'timestamp' : bigint,
  'locationLink' : string,
  'location' : string,
  'photos' : Array<string>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPropertyPhoto' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllContactSubmissionsWithToken' : ActorMethod<
    [string],
    Array<ContactSubmission>
  >,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllPropertiesWithToken' : ActorMethod<[string], Array<Property>>,
  'getApprovedProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConstructionEstimate' : ActorMethod<
    [string, string, bigint, string],
    string
  >,
  'getFinanceRoles' : ActorMethod<[], Array<[Principal, SmartFinanceRole]>>,
  'getFinanceRolesWithToken' : ActorMethod<
    [string],
    Array<[Principal, SmartFinanceRole]>
  >,
  'getMyProperties' : ActorMethod<[], Array<Property>>,
  'getSmartFinanceRequests' : ActorMethod<[], Array<SmartFinanceRequest>>,
  'getSmartFinanceRequestsWithToken' : ActorMethod<
    [string],
    Array<SmartFinanceRequest>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerFinanceApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listApprovalsWithToken' : ActorMethod<[string], Array<UserApprovalInfo>>,
  'removePropertyPhoto' : ActorMethod<[bigint, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestSmartFinanceAccess' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPropertyStatus' : ActorMethod<
    [bigint, PropertyStatus, bigint],
    undefined
  >,
  'setSmartFinanceRole' : ActorMethod<[Principal, SmartFinanceRole], undefined>,
  'submitContactSubmission' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitProperty' : ActorMethod<[SubmitPropertyInput], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProperty' : ActorMethod<
    [bigint, string, string, string, string, string, Array<string>, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];