/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PropertyStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'valuation' : IDL.Text,
  'updatedAt' : IDL.Int,
  'locationLink' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SmartFinanceRole = IDL.Variant({
  'financeApproved' : IDL.Null,
  'standard' : IDL.Null,
});
export const SmartFinanceRequest = IDL.Record({
  'request' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllContactSubmissionsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllPropertiesWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getApprovedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConstructionEstimate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getFinanceRoles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SmartFinanceRole))],
      ['query'],
    ),
  'getFinanceRolesWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SmartFinanceRole))],
      ['query'],
    ),
  'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getSmartFinanceRequests' : IDL.Func(
      [],
      [IDL.Vec(SmartFinanceRequest)],
      ['query'],
    ),
  'getSmartFinanceRequestsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SmartFinanceRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerFinanceApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listApprovalsWithToken' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserApprovalInfo)],
      ['query'],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'requestSmartFinanceAccess' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setPropertyStatus' : IDL.Func([IDL.Nat, PropertyStatus, IDL.Int], [], []),
  'setSmartFinanceRole' : IDL.Func([IDL.Principal, SmartFinanceRole], [], []),
  'submitContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitProperty' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProperty' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PropertyStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'valuation' : IDL.Text,
    'updatedAt' : IDL.Int,
    'locationLink' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SmartFinanceRole = IDL.Variant({
    'financeApproved' : IDL.Null,
    'standard' : IDL.Null,
  });
  const SmartFinanceRequest = IDL.Record({
    'request' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllContactSubmissionsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllPropertiesWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getApprovedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConstructionEstimate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getFinanceRoles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SmartFinanceRole))],
        ['query'],
      ),
    'getFinanceRolesWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SmartFinanceRole))],
        ['query'],
      ),
    'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getSmartFinanceRequests' : IDL.Func(
        [],
        [IDL.Vec(SmartFinanceRequest)],
        ['query'],
      ),
    'getSmartFinanceRequestsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SmartFinanceRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerFinanceApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listApprovalsWithToken' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserApprovalInfo)],
        ['query'],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'requestSmartFinanceAccess' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setPropertyStatus' : IDL.Func([IDL.Nat, PropertyStatus, IDL.Int], [], []),
    'setSmartFinanceRole' : IDL.Func([IDL.Principal, SmartFinanceRole], [], []),
    'submitContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitProperty' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProperty' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };